import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FCMProvider from "@/components/FCMProvider";
import Sidebar from "../components/sidebar";
import AuthGuard from "@/components/AuthGuard";
import { ChecklistProvider } from "./checklist/context";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "sonner";
import SidebarLayout from "@/components/SidebarLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen overflow-hidden">
        <ReduxProvider>
          <AuthGuard>
            <SidebarLayout>
              <FCMProvider>
                <ChecklistProvider>
                  {children}
                  <Toaster position="top-right" richColors />
                </ChecklistProvider>
              </FCMProvider>
            </SidebarLayout>
          </AuthGuard>
        </ReduxProvider>
      </body>
    </html>
  );
}
